<?php

namespace app\models;

use app\components\BaseActiveRecord;

class AuthItem extends BaseActiveRecord{

    //========== ROLES ==========//
    const ROLE_ROOT = 'ROLE_ROOT';
    const ROLE_ADMIN = 'ROLE_ADMIN';
    //========== /ROLES ==========//

    //========== PERMISSIONS ==========//
    // Пользователи
    const PERMISSION_USER_GET = 'PERMISSION_USER_GET';
    const PERMISSION_USER_CREATE = 'PERMISSION_USER_CREATE';
    const PERMISSION_USER_UPDATE = 'PERMISSION_USER_UPDATE';
    const PERMISSION_USER_DELETE = 'PERMISSION_USER_DELETE';

    // Настройки
    const PERMISSION_CONFIG_GET = 'PERMISSION_CONFIG_GET';
    const PERMISSION_CONFIG_CREATE = 'PERMISSION_CONFIG_CREATE';
    const PERMISSION_CONFIG_UPDATE = 'PERMISSION_CONFIG_UPDATE';
    const PERMISSION_CONFIG_DELETE = 'PERMISSION_CONFIG_DELETE';

    // Файлы
    const PERMISSION_FILE_GET = 'PERMISSION_FILE_GET';
    const PERMISSION_FILE_CREATE = 'PERMISSION_FILE_CREATE';
    const PERMISSION_FILE_UPDATE = 'PERMISSION_FILE_UPDATE';
    const PERMISSION_FILE_DELETE = 'PERMISSION_FILE_DELETE';

    // Статусы
    const PERMISSION_STATUS_GET = 'PERMISSION_STATUS_GET';
    const PERMISSION_STATUS_CREATE = 'PERMISSION_STATUS_CREATE';
    const PERMISSION_STATUS_UPDATE = 'PERMISSION_STATUS_UPDATE';
    const PERMISSION_STATUS_DELETE = 'PERMISSION_STATUS_DELETE';
}